### PR TITLE
task completed(1)

### PR DESCRIPTION
**Pull request by DaniilHinzburh**

### CODE REVIEW

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
delete identifier.sqlite from repo and commit

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
and also delete cinema.db3 anad add it in gitignore

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
you didn't delete db

**Comment by DaniilHinzburh** [comment]
Sorry, I have a problem with Git, I can’t figure out the controls, so I can make a similar mistake.

**Pull request closed without merging**
