### PR TITLE
+

### PR DESCRIPTION
**Pull request by AndriZhok**

### CODE REVIEW

**Comment by AndriZhok** [comment]
I don't understand why the data output has an error in placing this data, how can I fix it?

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
Delete db.sqlite3 from pull request

**Comment by AndriZhok** [comment]
I am don't understand your comment

**Review by vasylhnatiuk — CHANGES_REQUESTED** [review]
You have useless file app/cinema.sqlite, delete it. You shouldn’t push it in github

**Review by EdAlekseiev — CHANGES_REQUESTED** [review]
You should delete cinema.sqlite file and add it to .gitignore. If you stuck with it, you should write to chat of your group

**Review by EdAlekseiev — APPROVED** [review]

**Pull request closed without merging**
